### ISSUE TITLE
test how output data size depends on included tables

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-conversion-service#104]
For the following bounding boxes (see production instance for excerpts)

- Azerbaijan `(north=42.06560675405716, east=51.119384765625, south=38.36750215395045, west=44.505615234375)`
- Port-au-Prince `(north=18.680723648289042, east=-72.18154907226562, south=18.47179400162541, west=-72.4277114868164)`
- Guinea, Sierra Leone, Liberia `(north=12.833226023521243, east=-7.00927734375, south=3.908098881894123, west=-15.4248046875)`
- Greater Bogotá `(north=4.852890820110573, east=-73.97438049316406, south=4.517559280651309, west=-74.22981262207031)`
- South Philippines `(north=13.581920900545844, east=127.265625, south=4.620228796979006, west=119.64111328125)`

compare the sizes of outputs for

* all tables

   vs.
* "Datenmodell 2" tables only (M7-M9, `1`:`3e5` to `1`:`1e6`; See [Vereinfachtes_Datenmodell_OSMaxx_20160120.xlsx](https://github.com/geometalab/osmaxx-conversion-service/files/106807/Vereinfachtes_Datenmodell_OSMaxx_20160120.xlsx))

   vs.
* each table individually

## Implementation note:
Consider using [`ogr2ogr`'s `TABLES` option](http://www.gdal.org/drv_pg.html)

**Comment by beneditatan** [comment]
the output data
[Output data.xlsx](https://github.com/geometalab/osmaxx-conversion-service/files/179311/Output.data.xlsx)

**Comment by das-g** [comment]
In the spreadsheet attached to [last week's comment](https://github.com/geometalab/osmaxx-conversion-service/issues/104#issuecomment-198265051), Shapefile results (sheet 'shp') are bogus: Shapefile is a file format consisting of several files per data set. (In our case these four: `*.shp`, `*.dbf`, `*.shx` and `*.prj`.) Only one file per data set was considered for determining the size instead of summing up the sizes of all files belonging to a data set.

We decided that for now, it's not worth the hassle to re-do the measurements for Shapefiles. (In case we need to do it later, @hixi has them on an external hard disk for most of the excerpts examined here. Figures look similar as for the other formats.)

**Comment by das-g** [comment]
@geoSLG: Here are our size measurements for ESRI File Geodatabase (FileGDB; sheet 'fgdb'), GeoPackage (sheet 'gpkg') and Spatialite (sheet 'Spatialite'):
[OSMaxx_output_data_size.xlsx](https://github.com/geometalab/osmaxx-conversion-service/files/187981/OSMaxx_output_data_size.xlsx)

Shapefile format is not included for the reason [stated above](https://github.com/geometalab/osmaxx-conversion-service/issues/104#issuecomment-200854193). Garmin IMG output size was not measured, as we cannot easily choose what data to include there.

**Comment by geoSLG** [comment]
@das-g Thanks a lot for the interesting comparison of the output size of each table. Quite interesting to see that the table "roads" is the heaviest part of OSMaxx data model. 
What tables are included in the "M11" row? Buildings?

**Comment by das-g** [comment]
> What tables are included in the "M11" row?

All GIS-Layers (i.e. OSMaxx SQL tables) that have a `X` or `(X)` in the 'Datenmodell 2' columns M7 (1:300'000) to M11 (1:5'000'000) of [Vereinfachtes_Datenmodell_OSMaxx_20160120.xlsx](https://github.com/geometalab/osmaxx-conversion-service/files/106807/Vereinfachtes_Datenmodell_OSMaxx_20160120.xlsx) should be ([and are](https://github.com/geometalab/osmaxx-conversion-service/blob/9ac6b2c2beda467cfe2d707c92cf327e08d1550f/osmaxx/worker/experiments.py#L63)) included in the "M11" row:
- adminarea_a
- boundary_l
- geoname_l
- geoname_p
- landuse_a
- military_a
- military_p
- misc_l
- natural_a
- natural_p
- poi_p
- railway_l
- road_l
- route_l
- utility_l
- water_a
- water_p
- water_l

**Not** included should be GIS-Layers with _neither_ `X` or `(X)`:
- address_p
- building_a
- nonop_l
- poi_a
- pow_a
- pow_p
- traffic_a
- traffic_p
- transport_a
- transport_p
- utility_a
- utility_p

> Buildings?
@geoSLG `buildings_a` is not included in the "M11" row.
