### ISSUE TITLE
add cemetery and graveyard

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-conversion-service#124]
Include all areas with OSM tag [`amenity=grave_yard`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgrave_yard) **and** all areas with OSM tag [`landuse=cemetery`](http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dcemetery) in osmaxx layer `pow_a` (with osmaxx attributes `aggtype` 'public' and `type` 'graveyard').

* exclude both from layer `landuse`
* also include cemeteries and graveyards which have no religion attached
- [ ] document this decision in docs repo

**Comment by das-g** [comment]
OSM features with `amenity=grave_yard` are currently also included in `poi_a` and `poi_p` (that's "**p**oint **o**f **i**nterest", not "place of worship (`pow_*`)), but `landuse=cemetery` isn't.

@sfkeller: Should both `amenity=grave_yard` **and** `landuse=cemetery` be represented in the POI layer, or neither? Or should it be kept as-is for the PO**I** layer on only be changed (there: include both) in the PO**W** layer?

**Comment by das-g** [comment]
> but landuse=cemetery isn't

Or is it, as we don't exclude `amenity=NULL` [in `poi_a`](https://github.com/geometalab/osmaxx-conversion-service/blob/4b9e81e063a326c6e064522464d8563894ef3808/osmaxx/converters/gis_converter/bootstrap/sql/filter/poi/010_poi_amenity.sql#L80) nor [in `poi_p`](https://github.com/geometalab/osmaxx-conversion-service/blob/4b9e81e063a326c6e064522464d8563894ef3808/osmaxx/converters/gis_converter/bootstrap/sql/filter/poi/130_poi_p_amenity.sql#L76)?

**Comment by sfkeller** [comment]
I'd expect both `amenity=grave_yard` and `landuse=cemetery` be solely present in POW_a and POW_p layer.

**Comment by das-g** [comment]
Talked to @sfkeller: By
> I'd expect [...]

[above](https://github.com/geometalab/osmaxx-conversion-service/issues/124#issuecomment-191729975) he's not indicating his assumptions about the current behavior, he's stating the wanted (i.e. expected) behavior.

**Comment by das-g** [comment]
From the protocol of the conference call of 2016-03-01:
> [&hellip;]
> Konsistenz Datenmodell:
> - Graveyard (poi_a) und cemetery (pow_a) werden unterschiedlich gehandhabt – sollten zusammengenommen werden zu cemetery unter der Tabelle „landuse_a“
Diskussion ob pow_a als Tabelle noch gebraucht wird. Antwort: Ja da Kirchen als Gebäude hervorgehoben werden sollen. Kirchen evtl. zu anderer Tabelle poi_a?
> [&hellip;]

This would probably mean OSM features with tag `amenity=grave_yard` **and** OSM features with tag `landuse=cemetery` should both
- yield entries in osmaxx layers `landuse_a` or `landuse_p` with the value `'cemetery'` in column `type`, whether or not `religion=*` is present in the respective feature's OSM tags.
- **not** yield entries in any of the osmaxx layers `poi_a`, `poi_p`, `pow_a` or `pow_p`

This contradicts @sfkeller's proposition to put graveyards and cemeteries into `pow_*` as reflected in this issues description:
> Include all areas with OSM tag [`amenity=grave_yard`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgrave_yard) **and** all areas with OSM tag [`landuse=cemetery`](http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dcemetery) in osmaxx layer `pow_a` (with osmaxx attributes `aggtype` 'public' and `type` 'graveyard').
>
> * exclude both from layer `landuse`
> * also include cemeteries and graveyards which have no religion attached

I'll take this up with @sfkeller and will bring it up at today's conference call if necessary.

**Comment by das-g** [comment]
Discussed at conference cal on 2016-03-09 without coming to a conclusion.

**Comment by das-g** [comment]
Moving back to Backlog until expected/wanted behavior has been determined.

**Comment by hixi** [comment]
Discussed with and decided by @sfkeller :

Do **not** include in landuse (to avoid `aggtype` overhead).
Include in **POI**s as before, just add the forgotten ones.

**Comment by hixi** [comment]
After a discussion with stakeholders:

Add `cemetery` and `grave_yard` to `poi_a` and `poi_p` as `burial_grounds`

**Comment by hixi** [comment]
closing since tracker through geometalab/osmaxx-frontend#477
