### ISSUE TITLE
Fix missing specific geometry type GeoPackage generation by OGR

### ISSUE THREAD

**Issue by sfkeller** [geometalab/osmaxx-conversion-service#2]
Estimated duration: ~?d

### Problem

Current shell scripts (and finally OGR itself) generates a GeoPackage file output without specific Geometry type, like point, linestring or polygon.

One can verify this using `ogrinfo` commandline tool:

  ...
  Layer name: water_a
  Geometry: **Unknown (any)**
  Feature Count: 39

### Impact
If the user requests and downloads the data as GeoPackage and then tries to convert the downloaded GeoPackage to Shapefile on their own, this will fail or the user will be prompted for a specific geometry type for every (currently 26) table in the delivery.

**Comment by das-g** [comment]
We've switched OGR version since this was reported. Please test whether this problem still occurs.

**Comment by njordan-hsr** [comment]
@sfkeller can you try it again and verify, I'm getting something that looks OK now, and converting with `ogr2ogr osmaxx_excerpt_2015-10-08_075916.shp osmaxx_excerpt_2015-10-08_075916.gpkg` works (with some warnings about utf-8 to iso-smth conversion issues).

```
...
INFO: Open of `osmaxx_excerpt_2015-10-08_075916.gpkg'
      using driver `GPKG' successful.

Layer name: address_p
Geometry: Point
Feature Count: 4
...
```

**Comment by das-g** [comment]
Haven't heard back on this for 6 months.

Closing. @sfkeller If this error still occurs, please re-open.
