### ISSUE TITLE
Fix lacking tag attribute and wrong content in street attribute of table address_p

### ISSUE THREAD

**Issue by sfkeller** [geometalab/osmaxx-conversion-service#3]
Estimated duration: ~?d

### Problem

Table `address_p` lacks the `tag` attribute and contains wrong content in `street` attribute: Currently there show up key-values in the `street` attribute, which belong into `tag` attribute.

**Comment by das-g** [comment]
**Can't reproduce**: Here's some `address_p any` data from Cham, ZG, Switzerland. Content of `street` and `tags` columns look alright:

wkt_geom|osm_id|lastchange|geomtype|type|name|label|tags|street|housenumber|postcode|city|country
---|---|---|---|---|---|---|---|---|---|---|---|---
Point (941560.13984500069636852 5971485.22657554317265749)|97470148||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"540.217", "addr:street"=>"Luzernerstrasse", "osm_version"=>"3", "osm_changeset"=>"18355534", "osm_timestamp"=>"2013-10-14T18:21:44Z", "addr:housenumber"=>"16"|Luzernerstrasse|16|||
Point (941575.9068960587028414 5971517.52452388685196638)|97470151||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"365.035", "addr:street"=>"Luzernerstrasse", "osm_version"=>"3", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:49Z", "addr:housenumber"=>"14"|Luzernerstrasse|14|||
Point (941584.59115716884844005 5971540.3917418634518981)|97849435||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"500.905", "addr:street"=>"Luzernerstrasse", "osm_version"=>"3", "osm_changeset"=>"18355534", "osm_timestamp"=>"2013-10-14T18:21:44Z", "addr:housenumber"=>"12"|Luzernerstrasse|12|||
Point (941077.89309958985541016 5971441.48956690169870853)|127225800||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"382.802", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "osm_changeset"=>"16648430", "osm_timestamp"=>"2013-06-21T19:58:16Z", "addr:housenumber"=>"32"|Hünenbergerstrasse|32|||
Point (941082.17164089251309633 5971053.68884983658790588)|141264015||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"1426.77", "addr:city"=>"Cham", "addr:street"=>"Luzernerstrasse", "osm_version"=>"3", "addr:postcode"=>"6330", "osm_changeset"=>"23074639", "osm_timestamp"=>"2014-06-22T06:11:53Z", "building:levels"=>"4", "addr:housenumber"=>"48"|Luzernerstrasse|48|6330||
Point (941599.04821373394224793 5971420.04024448618292809)|160193293||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"455.739", "addr:street"=>"Kirchbühl", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"14131593", "osm_timestamp"=>"2012-12-02T21:38:04Z", "addr:housenumber"=>"4"|Kirchbühl|4|6330||
Point (941568.16499999992083758 5971427.83500000089406967)|160193294||W|b|||"osm_uid"=>"97547", "building"=>"residential", "osm_user"=>"datendelphin", "way_area"=>"551.648", "addr:city"=>"Cham", "addr:street"=>"Kirchbühl", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31148732", "osm_timestamp"=>"2015-05-14T17:40:43Z", "addr:housenumber"=>"2"|Kirchbühl|2|6330||
Point (941677.58923240611329675 5971337.92605770472437143)|160193295||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"524.32", "addr:street"=>"Kirchbühl", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"14131593", "osm_timestamp"=>"2012-12-02T21:38:04Z", "addr:housenumber"=>"10"|Kirchbühl|10|6330||
Point (941522.91079238313250244 5971486.75736293941736221)|160193299||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"438.711", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:49Z", "addr:housenumber"=>"2"|Hünenbergerstrasse|2|||
Point (941485.84450974897481501 5971525.48741959501057863)|160193300||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"604.091", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:50Z", "addr:housenumber"=>"6"|Hünenbergerstrasse|6|||
Point (941629.48317123192828149 5971405.4653639979660511)|160193302||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"296.032", "addr:street"=>"Kirchbühl", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"14131593", "osm_timestamp"=>"2012-12-02T21:38:04Z", "addr:housenumber"=>"8"|Kirchbühl|8|6330||
Point (941476.14392309088725597 5971286.06786796171218157)|160193303||W|b|Bahnhof|Bahnhof|"name"=>"Bahnhof", "phone"=>"+41 41 785 50 50", "osm_uid"=>"97547", "tourism"=>"hotel", "website"=>"http://www.hotel-restaurant-bahnhof.ch", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"457.259", "addr:street"=>"Bahnhofstrasse", "osm_version"=>"3", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:48Z", "internet_access"=>"yes", "addr:housenumber"=>"2"|Bahnhofstrasse|2|||
Point (941505.42697456921450794 5971325.63698682561516762)|160193304||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"591.485", "addr:street"=>"Poststrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31698292", "osm_timestamp"=>"2015-06-03T17:31:12Z", "addr:housename"=>"Ärztehaus", "addr:housenumber"=>"2"|Poststrasse|2|6330||
Point (941460.55761701473966241 5971332.1704848250374198)|160193311||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"1126.26", "addr:street"=>"Luzernerstrasse", "osm_version"=>"2", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:49Z", "addr:housenumber"=>"19"|Luzernerstrasse|19|||
Point (941497.53201099846046418 5971436.89947719685733318)|160193312||W|b|Raben|Raben|"name"=>"Raben", "amenity"=>"restaurant", "cuisine"=>"regional", "osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"608.169", "wheelchair"=>"yes", "addr:street"=>"Luzernerstrasse", "osm_version"=>"4", "addr:postcode"=>"6330", "osm_changeset"=>"31698292", "osm_timestamp"=>"2015-06-03T17:31:13Z", "addr:housenumber"=>"20"|Luzernerstrasse|20|6330||
Point (941377.18861703097354621 5971495.84704786539077759)|161703887||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"256.342", "addr:city"=>"Cham", "addr:street"=>"Schulhausrain", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"14087046", "osm_timestamp"=>"2012-11-29T14:22:07Z", "addr:housenumber"=>"1"|Schulhausrain|1|6330||
Point (941585.92696206597611308 5971386.66341773420572281)|161703890||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"483.982", "addr:street"=>"Kirchbühl", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"14131593", "osm_timestamp"=>"2012-12-02T21:38:04Z", "addr:housenumber"=>"6"|Kirchbühl|6|6330||
Point (941279.55360908736474812 5971451.69077343586832285)|161703894||W|b|||"osm_uid"=>"783143", "building"=>"yes", "osm_user"=>"jop1982", "way_area"=>"328.049", "addr:city"=>"Cham", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"19598348", "osm_timestamp"=>"2013-12-23T11:32:03Z", "building:levels"=>"3", "addr:housenumber"=>"22"|Hünenbergerstrasse|22|6330||
Point (941548.06500000006053597 5971338.77500000037252903)|161703896||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"340.096", "addr:street"=>"Poststrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31698292", "osm_timestamp"=>"2015-06-03T17:31:12Z", "addr:housenumber"=>"7"|Poststrasse|7|6330||
Point (941344.03929320501629263 5971455.74051467981189489)|161703919||W|b|||"osm_uid"=>"783143", "building"=>"yes", "osm_user"=>"jop1982", "way_area"=>"344.146", "addr:city"=>"Cham", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"19598348", "osm_timestamp"=>"2013-12-23T11:32:03Z", "building:levels"=>"3", "addr:housenumber"=>"16"|Hünenbergerstrasse|16|6330||
Point (941431.76325619651470333 5971273.26482162158936262)|161703922||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"436.886", "addr:street"=>"Bahnhofstrasse", "osm_version"=>"2", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:49Z", "addr:housenumber"=>"3"|Bahnhofstrasse|3|||
Point (941303.11034332599956542 5971453.52137478906661272)|161703923||W|b|||"osm_uid"=>"783143", "building"=>"yes", "osm_user"=>"jop1982", "way_area"=>"196.701", "addr:city"=>"Cham", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"19598348", "osm_timestamp"=>"2013-12-23T11:32:03Z", "building:levels"=>"3", "addr:housenumber"=>"20"|Hünenbergerstrasse|20|6330||
Point (941568.08919801737647504 5971310.71170153375715017)|161703928||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"493.034", "addr:street"=>"Poststrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31698292", "osm_timestamp"=>"2015-06-03T17:31:14Z", "addr:housenumber"=>"13"|Poststrasse|13|6330||
Point (941451.46976332552731037 5971493.74698608461767435)|161703939||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"660.02", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:51Z", "addr:housenumber"=>"8"|Hünenbergerstrasse|8|||
Point (941474.11999999999534339 5971405.54499999992549419)|161703942||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"825.403", "addr:street"=>"Luzernerstrasse", "osm_version"=>"2", "osm_changeset"=>"15658792", "osm_timestamp"=>"2013-04-08T19:40:17Z", "addr:housenumber"=>"22"|Luzernerstrasse|22|||
Point (941442.19575839268509299 5971388.90916943270713091)|161703950||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"843.977", "addr:street"=>"Luzernerstrasse", "osm_version"=>"2", "osm_changeset"=>"15658792", "osm_timestamp"=>"2013-04-08T19:40:17Z", "addr:housenumber"=>"24"|Luzernerstrasse|24|||
Point (941401.13617041660472751 5971338.27936646528542042)|161703951||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"601.944", "addr:street"=>"Luzernerstrasse", "osm_version"=>"3", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:48Z", "addr:housename"=>"Sonnhof", "addr:housenumber"=>"28"|Luzernerstrasse|28|||
Point (941615.52282979874871671 5971504.06797716021537781)|161703956||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"551.24", "addr:street"=>"Kirchbühl", "osm_version"=>"3", "addr:postcode"=>"6330", "osm_changeset"=>"14131593", "osm_timestamp"=>"2012-12-02T21:38:04Z", "addr:housenumber"=>"1"|Kirchbühl|1|6330||
Point (941156.25862586393486708 5971449.45359241403639317)|162425504||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"479.631", "addr:street"=>"Allmendweg", "osm_version"=>"2", "osm_changeset"=>"16648430", "osm_timestamp"=>"2013-06-21T19:58:16Z", "addr:housenumber"=>"1"|Allmendweg|1|||
Point (941166.73149856843519956 5971526.44576095882803202)|193480644||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"754.314", "addr:street"=>"Allmendweg", "osm_version"=>"2", "osm_changeset"=>"16619594", "osm_timestamp"=>"2013-06-19T17:07:52Z", "addr:housenumber"=>"4"|Allmendweg|4|||
Point (941227.61491471098270267 5971509.43493619747459888)|193480645||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"1013.72", "addr:street"=>"Allmendweg", "osm_version"=>"2", "osm_changeset"=>"16619594", "osm_timestamp"=>"2013-06-19T17:07:52Z", "addr:housenumber"=>"8"|Allmendweg|8|||
Point (941124.19499999983236194 5971551.59500000160187483)|193480646||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"428.95", "addr:street"=>"Allmendweg", "osm_version"=>"2", "osm_changeset"=>"16560459", "osm_timestamp"=>"2013-06-15T09:00:01Z", "addr:housenumber"=>"6"|Allmendweg|6|||
Point (941287.05613980023190379 5971496.37535673286765814)|193480647||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"722.221", "addr:street"=>"Allmendweg", "osm_version"=>"2", "osm_changeset"=>"16619594", "osm_timestamp"=>"2013-06-19T17:07:52Z", "addr:housenumber"=>"12"|Allmendweg|12|||
Point (941434.26710807799827307 5971364.28673374094069004)|216525102||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"355.889", "addr:street"=>"Luzernerstrasse", "osm_version"=>"1", "osm_changeset"=>"15658792", "osm_timestamp"=>"2013-04-08T19:40:17Z", "addr:housenumber"=>"26"|Luzernerstrasse|26|||
Point (941476.23049335996620357 5971443.63200598396360874)|217429828||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"385.149", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"1", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:45Z", "addr:housenumber"=>"1"|Hünenbergerstrasse|1|||
Point (941487.17550285335164517 5971493.97757917828857899)|217429830||W|b|Credit Suisse|Credit Suisse|"name"=>"Credit Suisse", "amenity"=>"bank", "osm_uid"=>"69557", "building"=>"yes", "operator"=>"Credit Suisse", "osm_user"=>"freaktechnik", "way_area"=>"589.128", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"2", "osm_changeset"=>"28717557", "osm_timestamp"=>"2015-02-08T23:05:11Z", "addr:housenumber"=>"4"|Hünenbergerstrasse|4|||
Point (941317.7297858118545264 5971453.640170075930655)|253156514||W|b|||"osm_uid"=>"783143", "building"=>"yes", "osm_user"=>"jop1982", "way_area"=>"253.37", "addr:city"=>"Cham", "addr:street"=>"Hünenbergerstrasse", "osm_version"=>"3", "addr:postcode"=>"6330", "osm_changeset"=>"19598442", "osm_timestamp"=>"2013-12-23T11:37:09Z", "building:levels"=>"3", "addr:housenumber"=>"18"|Hünenbergerstrasse|18|6330||
Point (941375.01720510818995535 5971313.38000482600182295)|254316193||W|b|||"osm_uid"=>"32700", "building"=>"yes", "osm_user"=>"pfuender_666", "way_area"=>"253.426", "addr:city"=>"Cham", "addr:street"=>"Luzernerstrasse", "osm_version"=>"1", "addr:country"=>"CH", "osm_changeset"=>"19712397", "osm_timestamp"=>"2013-12-30T11:19:14Z", "addr:housenumber"=>"30"|Luzernerstrasse|30|||CH
Point (942090.62663317448459566 5971513.19989829510450363)|341026787||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"564.107", "addr:city"=>"Cham", "addr:street"=>"Seestrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:45Z", "addr:housenumber"=>"19"|Seestrasse|19|6330||
Point (942006.52778869646135718 5971533.4438465740531683)|341026788||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"594.808", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:47Z", "addr:housenumber"=>"16"|Seehofstrasse|16|6330||
Point (941827.44784033030737191 5971394.883425647392869)|341026789||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"358.667", "addr:street"=>"Villette", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:48Z", "addr:housenumber"=>"1"|Villette|1|6330||
Point (942055.86163754225708544 5971486.32990579027682543)|341026791||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"538.46", "addr:city"=>"Cham", "addr:street"=>"Seestrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:45Z", "addr:housenumber"=>"17"|Seestrasse|17|6330||
Point (941556.88071030797436833 5971536.91389988362789154)|345075060||W|b|||"osm_uid"=>"97547", "building"=>"yes", "osm_user"=>"datendelphin", "way_area"=>"749.002", "addr:street"=>"Gemeindehausweg", "osm_version"=>"1", "osm_changeset"=>"31148732", "osm_timestamp"=>"2015-05-14T17:40:44Z", "addr:housenumber"=>"2"|Gemeindehausweg|2|||
Point (941060.18999999994412065 5971544.41000000014901161)|-1949684716||N|e|||"osm_uid"=>"8296", "entrance"=>"yes", "osm_user"=>"kuede", "addr:street"=>"Allmendweg", "osm_version"=>"2", "osm_changeset"=>"35877242", "osm_timestamp"=>"2015-12-11T03:03:18Z", "addr:housenumber"=>"7"|Allmendweg|7|||
Point (941197.58999999996740371 5971482.62000000011175871)|1539222378||N|p|||"osm_uid"=>"8296", "osm_user"=>"kuede", "addr:city"=>"Cham", "addr:street"=>"Allmendweg", "osm_version"=>"4", "addr:country"=>"CH", "addr:postcode"=>"6330", "osm_changeset"=>"35877242", "osm_timestamp"=>"2015-12-11T03:03:18Z", "addr:housenumber"=>"2"|Allmendweg|2|6330||CH
Point (941496.7900000000372529 5971376.58999999985098839)|-2028001419||N|p|||"osm_uid"=>"97547", "osm_user"=>"datendelphin", "addr:street"=>"Luzernerstrasse", "osm_version"=>"1", "osm_changeset"=>"15724764", "osm_timestamp"=>"2013-04-14T13:27:42Z", "addr:housenumber"=>"17"|Luzernerstrasse|17|||
Point (941521.21999999997206032 5971356.04999999981373549)|-725243791||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:street"=>"Poststrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"31698292", "osm_timestamp"=>"2015-06-03T17:31:12Z", "addr:housenumber"=>"4"|Poststrasse|4|6330||
Point (941649.06000000005587935 5971479.90000000037252903)|1105436093||N|p|Cafe Plaza|Cafe Plaza|"name"=>"Cafe Plaza", "amenity"=>"cafe", "osm_uid"=>"97547", "osm_user"=>"datendelphin", "wheelchair"=>"limited", "addr:street"=>"Kirchbühl", "osm_version"=>"4", "addr:postcode"=>"6330", "osm_changeset"=>"14131593", "osm_timestamp"=>"2012-12-02T21:38:07Z", "addr:housenumber"=>"5"|Kirchbühl|5|6330||
Point (941630.09999999997671694 5971502.84999999962747097)|2047090538||N|p|||"osm_uid"=>"97547", "osm_user"=>"datendelphin", "addr:street"=>"Kirchbühl", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"14131593", "osm_timestamp"=>"2012-12-02T21:37:46Z", "addr:housenumber"=>"3"|Kirchbühl|3|6330||
Point (941616.85999999998603016 5971527.23000000044703484)|-787695302||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:street"=>"Luzernerstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:36Z", "addr:housenumber"=>"11"|Luzernerstrasse|11|6330||
Point (941644.68000000005122274 5971563.58999999985098839)|-787695102||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:street"=>"Luzernerstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:38Z", "addr:housenumber"=>"9"|Luzernerstrasse|9|6330||
Point (941854.93999999994412065 5971513.63999999966472387)|-787694303||N|p|||"osm_uid"=>"97547", "osm_user"=>"datendelphin", "addr:street"=>"Seestrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:33Z", "addr:housenumber"=>"7"|Seestrasse|7|6330||
Point (941806.67000000004190952 5971531.41999999992549419)|-787694502||N|p|||"osm_uid"=>"97547", "osm_user"=>"datendelphin", "addr:street"=>"Seestrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:33Z", "addr:housenumber"=>"5"|Seestrasse|5|6330||
Point (941800 5971541.15000000037252903)|-787695200||N|p|||"osm_uid"=>"97547", "osm_user"=>"datendelphin", "addr:street"=>"Seestrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:32Z", "addr:housenumber"=>"3"|Seestrasse|3|6330||
Point (941781.68999999994412065 5971562.7900000000372529)|1736632347||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:street"=>"Seestrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:32Z", "addr:housenumber"=>"1"|Seestrasse|1|6330||
Point (941863.78000000002793968 5971502.66000000014901161)|-787715897||N|p|||"osm_uid"=>"97547", "osm_user"=>"datendelphin", "addr:street"=>"Seestrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"30942855", "osm_timestamp"=>"2015-05-09T17:26:34Z", "addr:housenumber"=>"9"|Seestrasse|9|6330||
Point (941949.7900000000372529 5971565.41999999992549419)|-753448501||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"31419290", "osm_timestamp"=>"2015-05-24T13:01:35Z", "addr:housenumber"=>"11d"|Seehofstrasse|11d|6330||
Point (941958.36999999999534339 5971557.86000000033527613)|-753448502||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"31419290", "osm_timestamp"=>"2015-05-24T13:01:34Z", "addr:housenumber"=>"11c"|Seehofstrasse|11c|6330||
Point (941965.71999999997206032 5971551.49000000022351742)|-753448702||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"31419290", "osm_timestamp"=>"2015-05-24T13:01:34Z", "addr:housenumber"=>"11b"|Seehofstrasse|11b|6330||
Point (941972.56000000005587935 5971545.66999999992549419)|-753449402||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"31419290", "osm_timestamp"=>"2015-05-24T13:01:33Z", "addr:housenumber"=>"11a"|Seehofstrasse|11a|6330||
Point (942020.46999999997206032 5971521.07000000029802322)|-812483961||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:41Z", "addr:housenumber"=>"6B"|Seehofstrasse|6b|6330||
Point (942044.69999999995343387 5971543.45000000018626451)|-812483954||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:41Z", "addr:housenumber"=>"6A"|Seehofstrasse|6a|6330||
Point (942120.06999999994877726 5971541.54999999981373549)|-743806196||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:42Z", "addr:housenumber"=>"8"|Seehofstrasse|8|6330||
Point (942129.19999999995343387 5971544.5400000000372529)|-743806197||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"1", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:42Z", "addr:housenumber"=>"10"|Seehofstrasse|10|6330||
Point (942141.25 5971548.50999999977648258)|-812483952||N|e|||"osm_uid"=>"97547", "entrance"=>"yes", "osm_user"=>"datendelphin", "addr:city"=>"Cham", "addr:street"=>"Seehofstrasse", "osm_version"=>"2", "addr:postcode"=>"6330", "osm_changeset"=>"31507645", "osm_timestamp"=>"2015-05-27T16:20:42Z", "addr:housenumber"=>"12"|Seehofstrasse|12|6330||

Source `https://<osmaxx dev instance>/downloads/29063f6b-1904-428a-8be9-9a2e68c683a9/`
