### ISSUE TITLE
Improve user prompts

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx-conversion-service#30]
Extracted from #11 

- [ ] Centralize prompting/logging to be able to controll the pollution of the command line
- [ ] https://github.com/geometalab/osmaxx-data-wrangling/pull/9/files#diff-a78f69c5e1aee0fd91c98ab41f2e116dR15 Filename of what?

**Comment by das-g** [comment]
An easy solution for limiting the terminal output when using this in the context of the web application is to just forward all output (or at least `std::out`) to `/dev/null`. Like this, debugging `osmaxx-postgis-conversion` would not be hampered.

**Comment by hixi** [comment]
Closing.
