### ISSUE TITLE
psycopg2.InternalError: ExteriorRing: geom is not a polygon

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-conversion-service#97]
https://sentry.dev.njo.ch/geometalab/prodworker/issues/43/

```
InternalError: ExteriorRing: geom is not a polygon

(7 additional frame(s) were not displayed)
...
  File "converters/gis_converter/bootstrap/bootstrap.py", line 30, in bootstrap
    self._filter_data()
  File "converters/gis_converter/bootstrap/bootstrap.py", line 102, in _filter_data
    self._execute_sql_scripts_in_folder(script_folder_path, autocommit=True)
  File "converters/gis_converter/bootstrap/bootstrap.py", line 107, in _execute_sql_scripts_in_folder
    self._postgres.execute_psycopg_file(script_path, autocommit=autocommit)
  File "converters/gis_converter/helper/postgres_wrapper.py", line 27, in execute_psycopg_file
    fetch_result=fetch_result
  File "converters/gis_converter/helper/postgres_wrapper.py", line 39, in execute_psycopg_command
    cursor.execute(sql)
```

**Comment by das-g** [comment]
Now that the files of the "filter" part (schema conversion) of the "bootstrap" SQL scripts have been split up (#107, #109), we can narrow down the cause of this.

One (maybe **THE**) cause of this is [when there is](https://github.com/geometalab/osmaxx-conversion-service/blob/5be89d0525228bf99c4debed03d4f39124c95934/osmaxx/converters/gis_converter/bootstrap/sql/filter/misc/010_barrier.sql#L52) a [`barrier=*`](http://wiki.openstreetmap.org/wiki/Key:barrier) OSM tag on a geometry that is converted to a <code>**MULTY**POLYGON</code> by `osm2pgsql`: For table `osmaxx.misc_l`, we [naively take the geometry's `ST_ExteriorRing`](https://github.com/geometalab/osmaxx-conversion-service/blob/5be89d0525228bf99c4debed03d4f39124c95934/osmaxx/converters/gis_converter/bootstrap/sql/filter/misc/010_barrier.sql#L35), but that is [only possible on geometries of type `POLYGON`](http://postgis.net/docs/ST_ExteriorRing.html), not on such of type <code>**MULTY**POLYGON</code>.

One occurrence of this is [OSM way 381621706](https://www.openstreetmap.org/way/381621706) (some strangely drawn/mapped wall near Port-au-Prince) Version 2 ([Changeset #35476781](https://www.openstreetmap.org/changeset/35476781)). (Might or might not have been brokenly mapped in Version 1 already.)
