### ISSUE TITLE
Add (corrected) Coastlines to OSMaxx output data

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-conversion-service#99]
- http://openstreetmapdata.com/data/coastlines
- http://openstreetmapdata.com/data/land-polygons
- http://openstreetmapdata.com/data/water-polygons

**Comment by hixi** [comment]
After a discussion with @das-g we decided to provide an external service/database that let's update these more easily and less often, for the start only manual, since they really don't change that often.

**Comment by das-g** [comment]
depends on geometalab/osm-boundaries#1
